/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamestore_gui_classes;

import gamestore_classes.Merchandise;
import gamestore_classes.Cart;

/**
 *
 * @author Muhammad Haikal Aiman Bin Mohd Puat S59419
 */
public class MerchandiseGUI extends javax.swing.JFrame{

Merchandise[] merch = new Merchandise[4];
    /**
     * Creates new form NewJFrame
     */
    public MerchandiseGUI() {
        initComponents();
        setResizable(false);
        
        merch[0] = new Merchandise("Keyboard", "Backlit-Lighting", "Lenovo", 76, 150, false);
        merch[1] = new Merchandise("Laptop", "Weather-Resistant", "Asus", 85, 900, false);
        merch[2] = new Merchandise("Console", "Peak gaming experience", "Sony", 97, 800, false);
        merch[3] = new Merchandise("Headphones", "Noise Cancellation", "Apple", 90, 115, false);
        
        this.setLocationRelativeTo(null);
        consoleCheckBox.setEnabled(false);
        keyboardCheckBox.setEnabled(false);
        headphoneCheckBox.setEnabled(false);
        laptopCheckBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        consoleBox = new javax.swing.JComboBox<>();
        keyboardBox = new javax.swing.JComboBox<>();
        headphoneBox = new javax.swing.JComboBox<>();
        laptopBox = new javax.swing.JComboBox<>();
        consoleCheckBox = new javax.swing.JCheckBox();
        keyboardCheckBox = new javax.swing.JCheckBox();
        headphoneCheckBox = new javax.swing.JCheckBox();
        laptopCheckBox = new javax.swing.JCheckBox();
        consoleInfoButton = new javax.swing.JButton();
        keyboardInfoButton = new javax.swing.JButton();
        headphonesInfoButton = new javax.swing.JButton();
        laptopInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Merchandise");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(22, 22, 22))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Items");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Description");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Price");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Quantity");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Add To Cart");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(167, 167, 167)
                .addComponent(jLabel6)
                .addGap(121, 121, 121)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(76, 76, 76)
                .addComponent(jLabel17)
                .addGap(53, 53, 53))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_gamestore/Merchandise Picture 1 ( Console ).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 94, 0, 0);
        jPanel7.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_gamestore/Merchandise Picture 3 (Keyboard).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel7.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_gamestore/Merchandise Picture 4 (Headphone).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 92, 0, 0);
        jPanel7.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_gamestore/LaptopIcon4.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 81, 13, 0);
        jPanel7.add(jLabel5, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("RM800");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 103, 0, 0);
        jPanel7.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("RM150");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 103, 0, 0);
        jPanel7.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("RM115");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 103, 0, 0);
        jPanel7.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setText("RM900");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 103, 0, 0);
        jPanel7.add(jLabel15, gridBagConstraints);

        consoleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        consoleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(72, 126, 0, 0);
        jPanel7.add(consoleBox, gridBagConstraints);

        keyboardBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        keyboardBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 126, 0, 0);
        jPanel7.add(keyboardBox, gridBagConstraints);

        headphoneBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        headphoneBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headphoneBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 126, 0, 0);
        jPanel7.add(headphoneBox, gridBagConstraints);

        laptopBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        laptopBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(82, 126, 0, 0);
        jPanel7.add(laptopBox, gridBagConstraints);

        consoleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 144, 0, 105);
        jPanel7.add(consoleCheckBox, gridBagConstraints);

        keyboardCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(69, 144, 0, 105);
        jPanel7.add(keyboardCheckBox, gridBagConstraints);

        headphoneCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headphoneCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 144, 0, 105);
        jPanel7.add(headphoneCheckBox, gridBagConstraints);

        laptopCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 144, 0, 105);
        jPanel7.add(laptopCheckBox, gridBagConstraints);

        consoleInfoButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        consoleInfoButton.setText("Console ");
        consoleInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleInfoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 38, 0, 0);
        jPanel7.add(consoleInfoButton, gridBagConstraints);

        keyboardInfoButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        keyboardInfoButton.setText("Keyboard ");
        keyboardInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardInfoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 38, 0, 0);
        jPanel7.add(keyboardInfoButton, gridBagConstraints);

        headphonesInfoButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        headphonesInfoButton.setText("Headphones ");
        headphonesInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headphonesInfoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 38, 0, 0);
        jPanel7.add(headphonesInfoButton, gridBagConstraints);

        laptopInfoButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        laptopInfoButton.setText("Laptop ");
        laptopInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopInfoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 38, 0, 0);
        jPanel7.add(laptopInfoButton, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headphoneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headphoneCheckBoxActionPerformed
        // TODO add your handling code here:
        if(headphoneCheckBox.isSelected()) {
          if(headphoneBox != null) {
              if(Cart.itemNameList.contains("Headphones") == false) {
                new Cart(merch[3].getItemName(), merch[3].getItemPrice(), headphoneQuantity);
                merch[3].setMERCH_BOUGHT(true);
              }
            }  
        } else {
            if(Cart.itemNameList.contains("Headphones") == true) {
                int index = Cart.itemNameList.indexOf("Headphones");
            
                 Cart.itemNameList.remove(index);
                 Cart.itemPriceList.remove(index);
                 Cart.itemQuantity.remove(index);
                 Cart.itemType.remove(index);
                 
                 merch[3].setMERCH_BOUGHT(false);
            }
        }
    }//GEN-LAST:event_headphoneCheckBoxActionPerformed

    private void consoleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleBoxActionPerformed
        // TODO add your handling code here:
        consoleQuantity = Integer.parseInt(consoleBox.getSelectedItem().toString());
        consoleCheckBox.setEnabled(true);       
    }//GEN-LAST:event_consoleBoxActionPerformed

    private void consoleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleCheckBoxActionPerformed
        // TODO add your handling code here:
      if(consoleCheckBox.isSelected()) {
          if(consoleBox != null) {
              if(Cart.itemNameList.contains("Console") == false) {
                new Cart(merch[2].getItemName(), merch[2].getItemPrice(), consoleQuantity);
                merch[2].setMERCH_BOUGHT(true);
              }
            }  
        } else {
            if(Cart.itemNameList.contains("Console") == true) {
                int index = Cart.itemNameList.indexOf("Console");
            
                 Cart.itemNameList.remove(index);
                 Cart.itemPriceList.remove(index);
                 Cart.itemQuantity.remove(index);
                 Cart.itemType.remove(index);
                 
                 merch[2].setMERCH_BOUGHT(false);
            }
        }
    }//GEN-LAST:event_consoleCheckBoxActionPerformed

    private void keyboardBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardBoxActionPerformed
        // TODO add your handling code here:
        keyboardQuantity = Integer.parseInt(keyboardBox.getSelectedItem().toString());
        keyboardCheckBox.setEnabled(true);
    }//GEN-LAST:event_keyboardBoxActionPerformed

    private void headphoneBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headphoneBoxActionPerformed
        // TODO add your handling code here:
        headphoneQuantity = Integer.parseInt(headphoneBox.getSelectedItem().toString());
        headphoneCheckBox.setEnabled(true);
    }//GEN-LAST:event_headphoneBoxActionPerformed

    private void laptopBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopBoxActionPerformed
        // TODO add your handling code here:
        laptopQuantity = Integer.parseInt(laptopBox.getSelectedItem().toString());
        laptopCheckBox.setEnabled(true);
    }//GEN-LAST:event_laptopBoxActionPerformed

    private void keyboardCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardCheckBoxActionPerformed
        // TODO add your handling code here:
        if(keyboardCheckBox.isSelected()) {
          if(keyboardBox != null) {
              if(Cart.itemNameList.contains("Keyboard") == false) {
                new Cart(merch[0].getItemName(), merch[0].getItemPrice(), keyboardQuantity);
                merch[0].setMERCH_BOUGHT(true);
              }
            }  
        } else {
            if(Cart.itemNameList.contains("Keyboard") == true) {
                int index = Cart.itemNameList.indexOf("Keyboard");
            
                 Cart.itemNameList.remove(index);
                 Cart.itemPriceList.remove(index);
                 Cart.itemQuantity.remove(index);
                 Cart.itemType.remove(index);
                 
                 merch[0].setMERCH_BOUGHT(false);
            }
        }
    }//GEN-LAST:event_keyboardCheckBoxActionPerformed

    private void laptopCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopCheckBoxActionPerformed
        // TODO add your handling code here:
        if(laptopCheckBox.isSelected()) {
          if(laptopBox != null) {
              if(Cart.itemNameList.contains("Laptop") == false) {
                new Cart(merch[1].getItemName(), merch[1].getItemPrice(), laptopQuantity);
                merch[1].setMERCH_BOUGHT(true);
              }
            }  
        } else {
            if(Cart.itemNameList.contains("Laptop") == true) {
                int index = Cart.itemNameList.indexOf("Laptop");
            
                 Cart.itemNameList.remove(index);
                 Cart.itemPriceList.remove(index);
                 Cart.itemQuantity.remove(index);
                 Cart.itemType.remove(index);
                 
                 merch[1].setMERCH_BOUGHT(false);
            }
        }
    }//GEN-LAST:event_laptopCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new CartGUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consoleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleInfoButtonActionPerformed
        // TODO add your handling code here:
        merch[2].itemDescription();
    }//GEN-LAST:event_consoleInfoButtonActionPerformed

    private void keyboardInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardInfoButtonActionPerformed
        // TODO add your handling code here:
        merch[0].itemDescription();
    }//GEN-LAST:event_keyboardInfoButtonActionPerformed

    private void headphonesInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headphonesInfoButtonActionPerformed
        // TODO add your handling code here:
        merch[3].itemDescription();
    }//GEN-LAST:event_headphonesInfoButtonActionPerformed

    private void laptopInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopInfoButtonActionPerformed
        // TODO add your handling code here:
        merch[1].itemDescription();
    }//GEN-LAST:event_laptopInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MerchandiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MerchandiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MerchandiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MerchandiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MerchandiseGUI().setVisible(true);
            }
        });
    }
    
    public static int consoleQuantity;
    public static int keyboardQuantity;
    public static int headphoneQuantity;
    public static int laptopQuantity;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> consoleBox;
    private javax.swing.JCheckBox consoleCheckBox;
    private javax.swing.JButton consoleInfoButton;
    private javax.swing.JComboBox<String> headphoneBox;
    private javax.swing.JCheckBox headphoneCheckBox;
    private javax.swing.JButton headphonesInfoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> keyboardBox;
    private javax.swing.JCheckBox keyboardCheckBox;
    private javax.swing.JButton keyboardInfoButton;
    private javax.swing.JComboBox<String> laptopBox;
    private javax.swing.JCheckBox laptopCheckBox;
    private javax.swing.JButton laptopInfoButton;
    // End of variables declaration//GEN-END:variables
}
